# Generated by Django 5.1 on 2025-06-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QAR_Mask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qar_id", models.CharField(max_length=60, verbose_name="QAR ID")),
                (
                    "dSimTime_mask",
                    models.BooleanField(default=False, verbose_name="模拟时间掩码"),
                ),
                (
                    "dStepTime_mask",
                    models.BooleanField(default=False, verbose_name="单步运行模拟时间掩码"),
                ),
                (
                    "dGravityAcc_mask",
                    models.BooleanField(default=False, verbose_name="重力加速度掩码"),
                ),
                (
                    "dUwg_mask",
                    models.BooleanField(default=False, verbose_name="风速沿地轴X轴分量掩码"),
                ),
                (
                    "dVwg_mask",
                    models.BooleanField(default=False, verbose_name="风速沿地轴Y轴分量掩码"),
                ),
                (
                    "dWwg_mask",
                    models.BooleanField(default=False, verbose_name="风速沿地轴Z轴分量掩码"),
                ),
                (
                    "dUTrub_mask",
                    models.BooleanField(default=False, verbose_name="紊流沿机体轴X轴分量掩码"),
                ),
                (
                    "dVTrub_mask",
                    models.BooleanField(default=False, verbose_name="紊流沿机体轴Y轴分量掩码"),
                ),
                (
                    "dWTrub_mask",
                    models.BooleanField(default=False, verbose_name="紊流沿机体轴Z轴分量掩码"),
                ),
                (
                    "dMass_mask",
                    models.BooleanField(default=False, verbose_name="飞机质量掩码"),
                ),
                (
                    "dAlpha_mask",
                    models.BooleanField(default=False, verbose_name="迎角掩码"),
                ),
                (
                    "dAlphaRad_mask",
                    models.BooleanField(default=False, verbose_name="迎角(弧度)掩码"),
                ),
                (
                    "dSinAlpha_mask",
                    models.BooleanField(default=False, verbose_name="迎角正弦值掩码"),
                ),
                (
                    "dCosAlpha_mask",
                    models.BooleanField(default=False, verbose_name="迎角余弦值掩码"),
                ),
                (
                    "dAlphaDot_mask",
                    models.BooleanField(default=False, verbose_name="迎角变化率掩码"),
                ),
                (
                    "dBeta_mask",
                    models.BooleanField(default=False, verbose_name="侧滑角掩码"),
                ),
                (
                    "dBetaRad_mask",
                    models.BooleanField(default=False, verbose_name="侧滑角(弧度)掩码"),
                ),
                (
                    "dSinBeta_mask",
                    models.BooleanField(default=False, verbose_name="侧滑角正弦值掩码"),
                ),
                (
                    "dCosBeta_mask",
                    models.BooleanField(default=False, verbose_name="侧滑角余弦值掩码"),
                ),
                (
                    "dBetaDot_mask",
                    models.BooleanField(default=False, verbose_name="侧滑角变化率掩码"),
                ),
                ("dPhi_mask", models.BooleanField(default=False, verbose_name="滚转角掩码")),
                (
                    "dTheta_mask",
                    models.BooleanField(default=False, verbose_name="俯仰角掩码"),
                ),
                ("dPsi_mask", models.BooleanField(default=False, verbose_name="偏航角掩码")),
                (
                    "dChi_mask",
                    models.BooleanField(default=False, verbose_name="航迹方位角掩码"),
                ),
                (
                    "dGamma_mask",
                    models.BooleanField(default=False, verbose_name="航迹爬升角掩码"),
                ),
                (
                    "dGroundspeed_mask",
                    models.BooleanField(default=False, verbose_name="航迹速度掩码"),
                ),
                ("dTAS_mask", models.BooleanField(default=False, verbose_name="真空速掩码")),
                (
                    "dMach_mask",
                    models.BooleanField(default=False, verbose_name="马赫数掩码"),
                ),
                ("dPd_mask", models.BooleanField(default=False, verbose_name="动压掩码")),
                ("dPs_mask", models.BooleanField(default=False, verbose_name="静压掩码")),
                (
                    "dUk_mask",
                    models.BooleanField(default=False, verbose_name="航迹速度X分量掩码"),
                ),
                (
                    "dVk_mask",
                    models.BooleanField(default=False, verbose_name="航迹速度Y分量掩码"),
                ),
                (
                    "dWk_mask",
                    models.BooleanField(default=False, verbose_name="航迹速度Z分量掩码"),
                ),
                (
                    "dUkDot_mask",
                    models.BooleanField(default=False, verbose_name="线加速度X分量掩码"),
                ),
                (
                    "dVkDot_mask",
                    models.BooleanField(default=False, verbose_name="线加速度Y分量掩码"),
                ),
                (
                    "dWkDot_mask",
                    models.BooleanField(default=False, verbose_name="线加速度Z分量掩码"),
                ),
                ("dU_mask", models.BooleanField(default=False, verbose_name="空速X分量掩码")),
                ("dV_mask", models.BooleanField(default=False, verbose_name="空速Y分量掩码")),
                ("dW_mask", models.BooleanField(default=False, verbose_name="空速Z分量掩码")),
                (
                    "dP_mask",
                    models.BooleanField(default=False, verbose_name="机体轴X轴角速度掩码"),
                ),
                (
                    "dQ_mask",
                    models.BooleanField(default=False, verbose_name="机体轴Y轴角速度掩码"),
                ),
                (
                    "dR_mask",
                    models.BooleanField(default=False, verbose_name="机体轴Z轴角速度掩码"),
                ),
                (
                    "dPRad_mask",
                    models.BooleanField(default=False, verbose_name="机体轴X轴角速度(弧度)掩码"),
                ),
                (
                    "dQRad_mask",
                    models.BooleanField(default=False, verbose_name="机体轴Y轴角速度(弧度)掩码"),
                ),
                (
                    "dRRad_mask",
                    models.BooleanField(default=False, verbose_name="机体轴Z轴角速度(弧度)掩码"),
                ),
                (
                    "dRDot_mask",
                    models.BooleanField(default=False, verbose_name="机体轴X轴角加速度掩码"),
                ),
                (
                    "dPDot_mask",
                    models.BooleanField(default=False, verbose_name="机体轴Y轴角加速度掩码"),
                ),
                (
                    "dQDot_mask",
                    models.BooleanField(default=False, verbose_name="机体轴Z轴角加速度掩码"),
                ),
                ("dNx_mask", models.BooleanField(default=False, verbose_name="X轴过载掩码")),
                ("dNy_mask", models.BooleanField(default=False, verbose_name="Y轴过载掩码")),
                ("dNz_mask", models.BooleanField(default=False, verbose_name="Z轴过载掩码")),
                (
                    "dUkgDot_mask",
                    models.BooleanField(default=False, verbose_name="线加速度地轴X分量掩码"),
                ),
                (
                    "dVkgDot_mask",
                    models.BooleanField(default=False, verbose_name="线加速度地轴Y分量掩码"),
                ),
                (
                    "dWkgDot_mask",
                    models.BooleanField(default=False, verbose_name="线加速度地轴Z分量掩码"),
                ),
                (
                    "dUkg_mask",
                    models.BooleanField(default=False, verbose_name="航迹速度地轴X分量掩码"),
                ),
                (
                    "dVkg_mask",
                    models.BooleanField(default=False, verbose_name="航迹速度地轴Y分量掩码"),
                ),
                (
                    "dWkg_mask",
                    models.BooleanField(default=False, verbose_name="航迹速度地轴Z分量掩码"),
                ),
                (
                    "dLongitude_mask",
                    models.BooleanField(default=False, verbose_name="经度掩码"),
                ),
                (
                    "dLatitude_mask",
                    models.BooleanField(default=False, verbose_name="纬度掩码"),
                ),
                (
                    "dASL_mask",
                    models.BooleanField(default=False, verbose_name="海拔高度掩码"),
                ),
                (
                    "dAGL_mask",
                    models.BooleanField(default=False, verbose_name="离地高度掩码"),
                ),
                (
                    "dTrueHeading_mask",
                    models.BooleanField(default=False, verbose_name="真航向掩码"),
                ),
                (
                    "dMagHeading_mask",
                    models.BooleanField(default=False, verbose_name="磁航向掩码"),
                ),
                (
                    "dPosXg_mask",
                    models.BooleanField(default=False, verbose_name="地轴X坐标掩码"),
                ),
                (
                    "dPosYg_mask",
                    models.BooleanField(default=False, verbose_name="地轴Y坐标掩码"),
                ),
                (
                    "dPosZg_mask",
                    models.BooleanField(default=False, verbose_name="地轴Z坐标掩码"),
                ),
                ("dtx_mask", models.BooleanField(default=False, verbose_name="副翼偏度掩码")),
                (
                    "dty_mask",
                    models.BooleanField(default=False, verbose_name="方向舵偏度掩码"),
                ),
                (
                    "dtz_mask",
                    models.BooleanField(default=False, verbose_name="升降舵偏度掩码"),
                ),
                (
                    "LGPos_mask",
                    models.BooleanField(default=False, verbose_name="起落架位置掩码"),
                ),
                (
                    "dFlap_mask",
                    models.BooleanField(default=False, verbose_name="襟翼偏度掩码"),
                ),
                (
                    "gfuel_mask",
                    models.BooleanField(default=False, verbose_name="剩余油量掩码"),
                ),
                (
                    "pe_t1_mask",
                    models.BooleanField(default=False, verbose_name="油门杆位置1掩码"),
                ),
                (
                    "pe_t2_mask",
                    models.BooleanField(default=False, verbose_name="油门杆位置2掩码"),
                ),
                (
                    "rot1_mask",
                    models.BooleanField(default=False, verbose_name="发动机转速1掩码"),
                ),
                (
                    "rot2_mask",
                    models.BooleanField(default=False, verbose_name="发动机转速2掩码"),
                ),
                (
                    "thrust_mask",
                    models.BooleanField(default=False, verbose_name="发动机推力掩码"),
                ),
                (
                    "gfused_mask",
                    models.BooleanField(default=False, verbose_name="耗油量掩码"),
                ),
                (
                    "dGtNormal_mask",
                    models.BooleanField(default=False, verbose_name="燃油消耗率掩码"),
                ),
                (
                    "dGfNormal_mask",
                    models.BooleanField(default=False, verbose_name="燃油消耗量掩码"),
                ),
                (
                    "dGFuel_mask",
                    models.BooleanField(default=False, verbose_name="余油量掩码"),
                ),
                (
                    "dDa_mask",
                    models.BooleanField(default=False, verbose_name="滚转操纵位置掩码"),
                ),
                (
                    "dDr_mask",
                    models.BooleanField(default=False, verbose_name="偏航操纵位置掩码"),
                ),
                (
                    "dDe_mask",
                    models.BooleanField(default=False, verbose_name="俯仰操纵位置掩码"),
                ),
                (
                    "dDaTrim_mask",
                    models.BooleanField(default=False, verbose_name="配平滚转操纵量掩码"),
                ),
                (
                    "dDeTrim_mask",
                    models.BooleanField(default=False, verbose_name="配平俯仰操纵量掩码"),
                ),
            ],
            options={
                "verbose_name": "QAR缺失掩码表",
                "verbose_name_plural": "QAR缺失掩码表",
            },
        ),
    ]
