# Generated by Django 5.1 on 2025-06-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QAR_Label_Missing_Stats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.IntegerField(
                        choices=[
                            (0, "正常状态"),
                            (1, "结冰状态"),
                            (2, "单发失效"),
                            (3, "双发失效"),
                            (4, "低能量"),
                        ],
                        verbose_name="飞行状态标签",
                    ),
                ),
                ("total_records", models.IntegerField(default=0, verbose_name="总记录数")),
                (
                    "missing_fields_count",
                    models.IntegerField(default=0, verbose_name="缺失字段总数"),
                ),
                (
                    "completeness_rate",
                    models.FloatField(default=100.0, verbose_name="完整率(%)"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="最后更新时间"),
                ),
            ],
            options={
                "verbose_name": "标签缺失统计",
                "verbose_name_plural": "标签缺失统计",
                "unique_together": {("label",)},
            },
        ),
    ]
