# Generated by Django 5.1 on 2025-06-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flight_Trajectory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qar_id",
                    models.CharField(max_length=60, null=True, verbose_name="QAR ID"),
                ),
                ("dSimTime", models.FloatField(null=True, verbose_name="模拟时间")),
                ("dTrueHeading", models.FloatField(null=True, verbose_name="真航向")),
                ("dMagHeading", models.FloatField(null=True, verbose_name="磁航向")),
                ("dLongitude", models.FloatField(null=True, verbose_name="经度")),
                ("dLatitude", models.FloatField(null=True, verbose_name="纬度")),
                ("dASL", models.FloatField(null=True, verbose_name="飞机重心海拔高度")),
                ("dAGL", models.FloatField(null=True, verbose_name="飞机重心离地高度")),
                (
                    "dLongitude_change",
                    models.FloatField(null=True, verbose_name="经度变化量"),
                ),
                (
                    "dLatitude_change",
                    models.FloatField(null=True, verbose_name="纬度变化量"),
                ),
                (
                    "dASL_change",
                    models.FloatField(null=True, verbose_name="飞机重心海拔高度变化量"),
                ),
                (
                    "dAGL_change",
                    models.FloatField(null=True, verbose_name="飞机重心离地高度变化量"),
                ),
            ],
            options={
                "verbose_name": "航迹",
                "verbose_name_plural": "航迹",
            },
        ),
    ]
