# Generated by Django 5.1 on 2025-04-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qar_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="qar",
            name="label",
            field=models.IntegerField(
                default=1, max_length=60, null=True, verbose_name="标签"
            ),
        ),
    ]
