# Generated by Django 5.1 on 2025-04-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qar_data", "0002_qar_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qar",
            name="label",
            field=models.IntegerField(default=1, null=True, verbose_name="标签"),
        ),
    ]
