# Generated by Django 5.1 on 2025-06-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QAR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qar_id",
                    models.CharField(max_length=60, null=True, verbose_name="QAR ID"),
                ),
                ("dSimTime", models.FloatField(null=True, verbose_name="模拟时间")),
                ("dStepTime", models.FloatField(null=True, verbose_name="单步运行模拟时间")),
                ("dGravityAcc", models.FloatField(null=True, verbose_name="重力加速度")),
                ("dUwg", models.FloatField(null=True, verbose_name="风速沿地轴X轴的分量")),
                ("dVwg", models.FloatField(null=True, verbose_name="风速沿地轴Y轴的分量")),
                ("dWwg", models.FloatField(null=True, verbose_name="风速沿地轴Z轴的分量")),
                ("dUTrub", models.FloatField(null=True, verbose_name="紊流沿机体轴X轴的分量")),
                ("dVTrub", models.FloatField(null=True, verbose_name="紊流沿机体轴Y轴的分量")),
                ("dWTrub", models.FloatField(null=True, verbose_name="紊流沿机体轴Z轴的分量")),
                ("dMass", models.FloatField(null=True, verbose_name="飞机质量")),
                ("dAlpha", models.FloatField(null=True, verbose_name="迎角")),
                ("dAlphaRad", models.FloatField(null=True, verbose_name="迎角")),
                ("dSinAlpha", models.FloatField(null=True, verbose_name="迎角正弦值")),
                ("dCosAlpha", models.FloatField(null=True, verbose_name="迎角余弦值")),
                ("dAlphaDot", models.FloatField(null=True, verbose_name="迎角变化率")),
                ("dBeta", models.FloatField(null=True, verbose_name="侧滑角")),
                ("dBetaRad", models.FloatField(null=True, verbose_name="侧滑角")),
                ("dSinBeta", models.FloatField(null=True, verbose_name="侧滑角正弦值")),
                ("dCosBeta", models.FloatField(null=True, verbose_name="侧滑角余弦值")),
                ("dBetaDot", models.FloatField(null=True, verbose_name="侧滑角变化率")),
                ("dPhi", models.FloatField(null=True, verbose_name="滚转角")),
                ("dTheta", models.FloatField(null=True, verbose_name="俯仰角")),
                ("dPsi", models.FloatField(null=True, verbose_name="偏航角")),
                ("dChi", models.FloatField(null=True, verbose_name="航迹方位角")),
                ("dGamma", models.FloatField(null=True, verbose_name="航迹爬升角")),
                ("dGroundspeed", models.FloatField(null=True, verbose_name="航迹速度")),
                ("dTAS", models.FloatField(null=True, verbose_name="真空速")),
                ("dMach", models.FloatField(null=True, verbose_name="马赫数")),
                ("dPd", models.FloatField(null=True, verbose_name="动压")),
                ("dPs", models.FloatField(null=True, verbose_name="静压")),
                ("dUk", models.FloatField(null=True, verbose_name="航迹速度沿机体轴X轴的分量")),
                ("dVk", models.FloatField(null=True, verbose_name="航迹速度沿机体轴Y轴的分量")),
                ("dWk", models.FloatField(null=True, verbose_name="航迹速度沿机体轴Z轴的分量")),
                ("dUkDot", models.FloatField(null=True, verbose_name="线加速度沿机体轴X轴的分量")),
                ("dVkDot", models.FloatField(null=True, verbose_name="线加速度沿机体轴Y轴的分量")),
                ("dWkDot", models.FloatField(null=True, verbose_name="线加速度沿机体轴Z轴的分量")),
                ("dU", models.FloatField(null=True, verbose_name="空速沿机体轴X轴的分量")),
                ("dV", models.FloatField(null=True, verbose_name="空速沿机体轴Y轴的分量")),
                ("dW", models.FloatField(null=True, verbose_name="空速沿机体轴Z轴的分量")),
                ("dP", models.FloatField(null=True, verbose_name="机体轴X轴角速度")),
                ("dQ", models.FloatField(null=True, verbose_name="机体轴Y轴角速度")),
                ("dR", models.FloatField(null=True, verbose_name="机体轴Z轴角速度")),
                ("dPRad", models.FloatField(null=True, verbose_name="机体轴X轴角速度")),
                ("dQRad", models.FloatField(null=True, verbose_name="机体轴Y轴角速度")),
                ("dRRad", models.FloatField(null=True, verbose_name="机体轴Z轴角速度")),
                ("dRDot", models.FloatField(null=True, verbose_name="机体轴X轴角加速度")),
                ("dPDot", models.FloatField(null=True, verbose_name="机体轴Y轴角加速度")),
                ("dQDot", models.FloatField(null=True, verbose_name="机体轴Z轴角加速度")),
                ("dNx", models.FloatField(null=True, verbose_name="机体轴重心处X轴的过载")),
                ("dNy", models.FloatField(null=True, verbose_name="机体轴重心处Y轴的过载")),
                ("dNz", models.FloatField(null=True, verbose_name="机体轴重心处Z轴的过载")),
                ("dUkgDot", models.FloatField(null=True, verbose_name="线加速度沿机地轴X轴的分量")),
                ("dVkgDot", models.FloatField(null=True, verbose_name="线加速度沿机地轴Y轴的分量")),
                ("dWkgDot", models.FloatField(null=True, verbose_name="线加速度沿机地轴Z轴的分量")),
                ("dUkg", models.FloatField(null=True, verbose_name="航迹速度沿地轴系X轴速度")),
                ("dVkg", models.FloatField(null=True, verbose_name="航迹速度沿地轴系Y轴速度")),
                ("dWkg", models.FloatField(null=True, verbose_name="航迹速度沿地轴系Z轴速度")),
                ("dLongitude", models.FloatField(null=True, verbose_name="经度")),
                ("dLatitude", models.FloatField(null=True, verbose_name="纬度")),
                ("dASL", models.FloatField(null=True, verbose_name="飞机重心海拔高度")),
                ("dAGL", models.FloatField(null=True, verbose_name="飞机重心离地高度")),
                ("dTrueHeading", models.FloatField(null=True, verbose_name="真航向")),
                ("dMagHeading", models.FloatField(null=True, verbose_name="磁航向")),
                (
                    "dPosXg",
                    models.FloatField(null=True, verbose_name="当前飞机质心在前一时刻地轴系的X轴坐标"),
                ),
                (
                    "dPosYg",
                    models.FloatField(null=True, verbose_name="当前飞机质心在前一时刻地轴系的Y轴坐标"),
                ),
                (
                    "dPosZg",
                    models.FloatField(null=True, verbose_name="当前飞机质心在前一时刻地轴系的Z轴坐标"),
                ),
                ("dtx", models.FloatField(null=True, verbose_name="副翼偏度")),
                ("dty", models.FloatField(null=True, verbose_name="方向舵偏度")),
                ("dtz", models.FloatField(null=True, verbose_name="升降舵偏度")),
                ("LGPos", models.FloatField(null=True, verbose_name="起落架位置")),
                ("dFlap", models.FloatField(null=True, verbose_name="襟翼偏度")),
                ("gfuel", models.FloatField(null=True, verbose_name="剩余油量")),
                ("pe_t1", models.FloatField(null=True, verbose_name="发动机油门杆位置1")),
                ("pe_t2", models.FloatField(null=True, verbose_name="发动机油门杆位置2")),
                ("rot1", models.FloatField(null=True, verbose_name="发动机转速1")),
                ("rot2", models.FloatField(null=True, verbose_name="发动机转速2")),
                ("thrust", models.FloatField(null=True, verbose_name="发动机推力")),
                ("gfused", models.FloatField(null=True, verbose_name="耗油量")),
                ("dGtNormal", models.FloatField(null=True, verbose_name="燃油消耗率")),
                ("dGfNormal", models.FloatField(null=True, verbose_name="燃油消耗量")),
                ("dGFuel", models.FloatField(null=True, verbose_name="余油量")),
                (
                    "dDa",
                    models.FloatField(null=True, verbose_name="横向驾驶员（滚转）操纵位置（横向杆位移）"),
                ),
                (
                    "dDr",
                    models.FloatField(null=True, verbose_name="航向驾驶员（偏航）操纵位置（脚蹬位移）"),
                ),
                (
                    "dDe",
                    models.FloatField(null=True, verbose_name="纵向驾驶员（俯仰）操纵位置（纵向杆位移）"),
                ),
                ("dDaTrim", models.FloatField(null=True, verbose_name="配平滚转操纵量")),
                ("dDeTrim", models.FloatField(null=True, verbose_name="配平俯仰操纵量")),
                (
                    "label",
                    models.IntegerField(default=0, null=True, verbose_name="飞行状态标签"),
                ),
            ],
            options={
                "verbose_name": "QAR数据",
                "verbose_name_plural": "QAR数据",
            },
        ),
        migrations.CreateModel(
            name="QAR_Parameter_Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parameter_name",
                    models.CharField(max_length=60, unique=True, verbose_name="参数名称"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="参数描述"),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="单位"
                    ),
                ),
                (
                    "min_value",
                    models.FloatField(blank=True, null=True, verbose_name="最小值"),
                ),
                (
                    "max_value",
                    models.FloatField(blank=True, null=True, verbose_name="最大值"),
                ),
                (
                    "mean_value",
                    models.FloatField(blank=True, null=True, verbose_name="平均值"),
                ),
                (
                    "variance",
                    models.FloatField(blank=True, null=True, verbose_name="方差"),
                ),
                (
                    "normalized_variance",
                    models.FloatField(blank=True, null=True, verbose_name="归一化方差"),
                ),
                (
                    "warning_lower",
                    models.FloatField(
                        blank=True, help_text="低于此值触发警告", null=True, verbose_name="警告下限"
                    ),
                ),
                (
                    "warning_upper",
                    models.FloatField(
                        blank=True, help_text="高于此值触发警告", null=True, verbose_name="警告上限"
                    ),
                ),
                (
                    "critical_lower",
                    models.FloatField(
                        blank=True,
                        help_text="低于此值触发严重警报",
                        null=True,
                        verbose_name="严重下限",
                    ),
                ),
                (
                    "critical_upper",
                    models.FloatField(
                        blank=True,
                        help_text="高于此值触发严重警报",
                        null=True,
                        verbose_name="严重上限",
                    ),
                ),
                (
                    "is_monitored",
                    models.BooleanField(
                        default=True, help_text="是否对此参数进行监控", verbose_name="是否监控"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="最后更新时间"),
                ),
            ],
            options={
                "verbose_name": "QAR参数属性",
                "verbose_name_plural": "QAR参数属性",
                "ordering": ["parameter_name"],
            },
        ),
    ]
